-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.assets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['real_estate'::text, 'vehicle'::text, 'bank_account'::text, 'investment'::text, 'insurance'::text, 'personal_property'::text, 'business'::text, 'other'::text])),
  description text,
  value numeric,
  location text,
  ownership_type text NOT NULL CHECK (ownership_type = ANY (ARRAY['sole'::text, 'joint'::text, 'tenants_in_common'::text, 'community_property'::text])),
  documents ARRAY DEFAULT '{}'::text[],
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  vault_id uuid,
  heir_ids ARRAY DEFAULT '{}'::uuid[],
  CONSTRAINT assets_pkey PRIMARY KEY (id),
  CONSTRAINT assets_vault_id_fkey FOREIGN KEY (vault_id) REFERENCES public.vaults(id),
  CONSTRAINT assets_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  action text NOT NULL,
  resource_type text NOT NULL CHECK (resource_type = ANY (ARRAY['vault'::text, 'vault_item'::text, 'inheritance_plan'::text, 'heir'::text, 'user'::text, 'shared_vault'::text])),
  resource_id uuid,
  ip_address inet,
  user_agent text,
  old_values jsonb,
  new_values jsonb,
  risk_level text CHECK (risk_level = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.heirs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  heir_user_id uuid,
  notify_on_activation boolean DEFAULT true,
  notification_delay_days integer DEFAULT 0 CHECK (notification_delay_days >= 0),
  is_active boolean DEFAULT true,
  has_accepted boolean DEFAULT false,
  accepted_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  invitation_code text UNIQUE,
  invitation_status text DEFAULT 'pending'::text CHECK (invitation_status = ANY (ARRAY['pending'::text, 'accepted'::text, 'rejected'::text, 'expired'::text])),
  invitation_expires_at timestamp with time zone,
  invited_at timestamp with time zone DEFAULT now(),
  rejected_at timestamp with time zone,
  relationship text,
  notification_status text DEFAULT 'pending'::text,
  notified_at timestamp with time zone,
  full_name_encrypted text,
  email_encrypted text,
  phone_encrypted text,
  relationship_encrypted text,
  heir_type text DEFAULT 'family'::text CHECK (heir_type = ANY (ARRAY['family'::text, 'friend'::text, 'professional'::text, 'organization'::text])),
  CONSTRAINT heirs_pkey PRIMARY KEY (id),
  CONSTRAINT heirs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT heirs_heir_user_id_fkey FOREIGN KEY (heir_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.inheritance_triggers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  trigger_metadata jsonb,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::trigger_status_type,
  requires_verification boolean DEFAULT true,
  verification_code text,
  verified_at timestamp with time zone,
  verified_by uuid,
  triggered_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  trigger_reason text,
  CONSTRAINT inheritance_triggers_pkey PRIMARY KEY (id),
  CONSTRAINT inheritance_triggers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT inheritance_triggers_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.users(id)
);
CREATE TABLE public.legal (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  document_type text NOT NULL CHECK (document_type = ANY (ARRAY['will'::text, 'trust'::text, 'power_of_attorney'::text, 'healthcare_directive'::text, 'living_will'::text, 'deed'::text, 'contract'::text, 'other'::text])),
  description text,
  template_content text,
  template_fields jsonb DEFAULT '[]'::jsonb,
  category text,
  is_system_template boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT legal_pkey PRIMARY KEY (id),
  CONSTRAINT legal_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.notaries (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  firm_name text,
  email text NOT NULL,
  phone text NOT NULL,
  address text NOT NULL,
  city text NOT NULL,
  state text NOT NULL,
  zip_code text NOT NULL,
  license_number text,
  specialization text,
  notes text,
  is_primary boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notaries_pkey PRIMARY KEY (id),
  CONSTRAINT notaries_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['heir_invitation'::text, 'inheritance_triggered'::text, 'vault_shared'::text, 'false_alarm'::text, 'heir_accepted'::text, 'heir_rejected'::text, 'subscription_update'::text, 'system_alert'::text])),
  title text NOT NULL,
  message text NOT NULL,
  action_url text,
  action_label text,
  is_read boolean DEFAULT false,
  is_archived boolean DEFAULT false,
  priority text DEFAULT 'normal'::text CHECK (priority = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text, 'urgent'::text])),
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  read_at timestamp with time zone,
  archived_at timestamp with time zone,
  expires_at timestamp with time zone,
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.shared_vaults (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  vault_id uuid NOT NULL,
  owner_id uuid NOT NULL,
  shared_with_user_id uuid NOT NULL,
  is_active boolean DEFAULT true,
  accepted boolean DEFAULT false,
  accepted_at timestamp with time zone,
  shared_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone,
  CONSTRAINT shared_vaults_pkey PRIMARY KEY (id),
  CONSTRAINT shared_vaults_vault_id_fkey FOREIGN KEY (vault_id) REFERENCES public.vaults(id),
  CONSTRAINT shared_vaults_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.users(id),
  CONSTRAINT shared_vaults_shared_with_user_id_fkey FOREIGN KEY (shared_with_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  email text NOT NULL UNIQUE CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text),
  full_name text,
  avatar_url text,
  emergency_contact_email text,
  emergency_contact_phone text,
  is_active boolean DEFAULT true,
  account_locked boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  last_login timestamp with time zone,
  email_verified boolean DEFAULT false,
  subscription_tier text DEFAULT 'free'::text CHECK (subscription_tier = ANY (ARRAY['free'::text, 'premium'::text, 'pro'::text])),
  subscription_status text DEFAULT 'inactive'::text CHECK (subscription_status = ANY (ARRAY['active'::text, 'inactive'::text, 'cancelled'::text, 'past_due'::text])),
  subscription_expires_at timestamp with time zone,
  global_trigger_method text DEFAULT 'inactivity'::text CHECK (global_trigger_method = ANY (ARRAY['inactivity'::text, 'death_certificate'::text, 'manual_trigger'::text, 'scheduled'::text, 'trusted_contact'::text, 'heir_notification'::text])),
  global_trigger_settings jsonb DEFAULT '{"inactivity_days": 30}'::jsonb,
  global_scheduled_date timestamp with time zone,
  last_activity timestamp with time zone DEFAULT now(),
  last_reminder_sent_at timestamp with time zone,
  trusted_contact_heir_id uuid,
  locked_until timestamp with time zone,
  failed_login_attempts integer DEFAULT 0,
  user_type text DEFAULT 'user'::text CHECK (user_type = ANY (ARRAY['user'::text, 'notary'::text])),
  inheritance_triggered boolean DEFAULT false,
  inheritance_triggered_at timestamp with time zone,
  account_deactivation_date timestamp with time zone,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT users_trusted_contact_heir_id_fkey FOREIGN KEY (trusted_contact_heir_id) REFERENCES public.heirs(id)
);
CREATE TABLE public.vault_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  vault_id uuid NOT NULL,
  user_id uuid NOT NULL,
  item_type USER-DEFINED NOT NULL,
  storage_path text NOT NULL UNIQUE,
  storage_bucket text NOT NULL DEFAULT 'vault-files'::text,
  file_size bigint,
  title_encrypted text NOT NULL,
  tags ARRAY,
  is_favorite boolean DEFAULT false,
  password_strength integer CHECK (password_strength IS NULL OR password_strength >= 0 AND password_strength <= 100),
  password_last_changed timestamp with time zone,
  requires_password_change boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  last_accessed timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT vault_items_pkey PRIMARY KEY (id),
  CONSTRAINT vault_items_vault_id_fkey FOREIGN KEY (vault_id) REFERENCES public.vaults(id),
  CONSTRAINT vault_items_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.vaults (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  icon text,
  color text,
  settings jsonb DEFAULT '{"autoLock": true, "autoLockTimeout": 15, "twoFactorEnabled": false, "maxFailedAttempts": 5}'::jsonb,
  access_control jsonb DEFAULT '{"allowedHeirs": [], "allowedUsers": [], "requireApproval": true}'::jsonb,
  death_settings jsonb DEFAULT '{"notifySMS": [], "notifyEmail": [], "instructions": "", "notifyContacts": true, "triggerAfterDays": 30}'::jsonb,
  is_locked boolean DEFAULT false,
  is_shared boolean DEFAULT false,
  sort_order integer DEFAULT 0 CHECK (sort_order >= 0),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  last_accessed timestamp with time zone,
  category text NOT NULL DEFAULT 'share'::text CHECK (category = ANY (ARRAY['share'::text, 'delete'::text, 'pro'::text])),
  CONSTRAINT vaults_pkey PRIMARY KEY (id),
  CONSTRAINT vaults_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);